/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import db.AuthenticationException;
import db.SQLHelper;
import db.User;
import db.UserException;
import java.sql.ResultSet;
import javax.swing.*;

/**
 *
 * @author jarrm5
 */
public class Login extends javax.swing.JFrame {
    
    private SQLHelper helper;

    /**
     * Creates new form Login
     */
    public Login(SQLHelper helper) {
        this.helper = helper;
        initComponents();
        //Initialize credentials
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textfield_username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combobox_type = new javax.swing.JComboBox<>();
        button_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setName(""); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setName(""); // NOI18N

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Username:");

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Type:");

        combobox_type.setBackground(new java.awt.Color(51, 51, 51));
        combobox_type.setForeground(new java.awt.Color(204, 204, 204));
        combobox_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Moderator" }));

        button_login.setText("Login");
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_login, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox_type, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addComponent(button_login)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        // Checking for empty field
        if(textfield_username.getText().length()==0)  
            JOptionPane.showMessageDialog(null, "Please type the username");
        else{  
             // Collecting the input
            String username = textfield_username.getText();  
            String type = combobox_type.getSelectedItem().toString().toLowerCase();
            //Create the user object here
            User user = new User();
            
            try{
                if(validateLogin(username,type,user)){
                    //JOptionPane.showMessageDialog(null, "Success!");
                    JFrame userAds = new UserAds(user,helper);
                    userAds.setVisible(true);
                }
            }
            catch(UserException u){
                JOptionPane.showMessageDialog(null, u.getMessage());
            }
            catch(AuthenticationException a){
                JOptionPane.showMessageDialog(null, a.getMessage());
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
            
        }        
    }//GEN-LAST:event_button_loginActionPerformed

    
    //Validate correct username, then validate moderators if that option was selected
    //Throw the appropriate exception if either one fails
    //Return true if the user logged in correctly
    private boolean validateLogin(String username,String type, User user) throws Exception{
        ResultSet rs;
        
        try{
            rs = helper.getUserName(username, "user");
            
            //Invalid username
            if(!rs.next()){
                throw new UserException("Invalid Username.");
            }
            
            //Username approved, set the username fields
            user.setUserId(rs.getString("User_ID"));
            user.setFirstName(rs.getString("UsrFirst_Name"));
            user.setLastName(rs.getString("UsrLast_Name"));
            
            //User wishes to log is an a moderator
            if(type.toLowerCase().equals("moderator")){
                rs = helper.getUserName(username, type);
                
                //Not a moderator
                if(!rs.next()){
                    throw new AuthenticationException(username + " is not a registered moderator.");
                }
                //Success: mark the user as a moderator
                user.setIsModerator();
            }
        }
        //Possible errors that could occur, pass the exception to login button event for display
        //Invalid username
        catch(UserException u){
            throw u;
        }
        //Not a moderator
        catch(AuthenticationException a){
            throw a;
        }
        //Database issues
        catch(Exception e){
            throw e;
        }
        
        return true;
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_login;
    private javax.swing.JComboBox<String> combobox_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textfield_username;
    // End of variables declaration//GEN-END:variables
}
