/**
 * Author:  jarrm5
 * Created: Apr 3, 2017
 */

--CREATE TABLE Categories
--(Category_ID VARCHAR(3) NOT NULL,
-- Cat_Name VARCHAR(50) NOT NULL,
-- CONSTRAINT PK_CATEGORIES PRIMARY KEY(Category_ID));

--CREATE TABLE Statuses
--(Status_ID VARCHAR(2) NOT NULL,
-- Status_Name VARCHAR(50) NOT NULL,
-- CONSTRAINT PK_STATUSES PRIMARY KEY(Status_ID));

--CREATE TABLE Users
--(User_ID VARCHAR(20) NOT NULL,
-- UsrFirst_Name VARCHAR(50) NOT NULL,
-- UsrLast_Name VARCHAR(50) NOT NULL,
-- CONSTRAINT PK_USERS PRIMARY KEY(User_ID));

--CREATE TABLE Moderators
--(User_ID VARCHAR(20) NOT NULL,
-- CONSTRAINT PK_MODERATORS PRIMARY KEY(User_ID),
-- CONSTRAINT FK_MODERATORS FOREIGN KEY(User_ID) REFERENCES Users(User_ID) ON DELETE RESTRICT);

--CREATE TABLE Advertisements
--(Advertisement_ID SMALLINT UNSIGNED AUTO_INCREMENT,
-- AdvTitle VARCHAR(50) NOT NULL,
-- AdvDetails VARCHAR(300) NOT NULL,
-- AdvDateTime DATE NOT NULL,
-- Price DOUBLE(10,2) NOT NULL,
-- User_ID VARCHAR(20) NOT NULL,
-- Moderator_ID VARCHAR(20),
-- Category_ID VARCHAR(3) NOT NULL,
-- Status_ID VARCHAR(2) NOT NULL,
-- CONSTRAINT PK_ADVERTISEMENTS PRIMARY KEY(Advertisement_ID),
-- CONSTRAINT FK_AD_USERS FOREIGN KEY(User_ID) REFERENCES Users(User_ID) ON DELETE CASCADE,
-- CONSTRAINT FK_AD_MODERATORS FOREIGN KEY(Moderator_ID) REFERENCES Moderators(User_ID),
-- CONSTRAINT FK_AD_CATEGORIES FOREIGN KEY(Category_ID) REFERENCES Categories(Category_ID) ON DELETE RESTRICT,
-- CONSTRAINT FK_AD_STATUSES FOREIGN KEY(Status_ID) REFERENCES Statuses(Status_ID) ON DELETE RESTRICT
--);
